#ifndef BWIDGETS_DEFAULT_DRAWARC_PATH
#define BWIDGETS_DEFAULT_DRAWARC_PATH "Draws/Oops/drawArc.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWKNOB_PATH
#define BWIDGETS_DEFAULT_DRAWKNOB_PATH "Draws/Oops/drawKnob.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWARCHANDLE_PATH
#define BWIDGETS_DEFAULT_DRAWARCHANDLE_PATH "Draws/Oops/drawArcHandle.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWHBAR_PATH
#define BWIDGETS_DEFAULT_DRAWHBAR_PATH "Draws/Oops/drawHBar.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWVBAR_PATH
#define BWIDGETS_DEFAULT_DRAWVBAR_PATH "Draws/Oops/drawVBar.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWHMETER_PATH
#define BWIDGETS_DEFAULT_DRAWHMETER_PATH "Draws/Oops/drawHMeter.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWVMETER_PATH
#define BWIDGETS_DEFAULT_DRAWVMETER_PATH "Draws/Oops/drawVMeter.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWRMETER_PATH
#define BWIDGETS_DEFAULT_DRAWRMETER_PATH "Draws/Oops/drawRMeter.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWBUTTON_PATH
#define BWIDGETS_DEFAULT_DRAWBUTTON_PATH "Draws/Oops/drawButton.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DRAWPAD_PATH
#define BWIDGETS_DEFAULT_DRAWPAD_PATH "Draws/Oops/drawPad.hpp"
#endif

#ifndef BWIDGETS_DEFAULT_DIAL_KNOB_REL_SIZE 
#define BWIDGETS_DEFAULT_DIAL_KNOB_REL_SIZE 0.0
#endif

#ifndef BWIDGETS_DEFAULT_SLIDER_KNOB_REL_SIZE 
#define BWIDGETS_DEFAULT_SLIDER_KNOB_REL_SIZE 0.5
#endif

#ifndef BWIDGETS_DEFAULT_SWITCH_KNOB_REL_SIZE 
#define BWIDGETS_DEFAULT_SWITCH_KNOB_REL_SIZE 1.0
#endif

#ifndef BWIDGETS_DEFAULT_SCROLLBAR_KNOB_REL_SIZE 
#define BWIDGETS_DEFAULT_SCROLLBAR_KNOB_REL_SIZE 0.5
#endif